### ISSUE TITLE
CI fails on alpine linux

### ISSUE THREAD

**Issue by melezhik** [pdf-raku/FontConfig-raku#1]
Hi!

Here is the log - http://sparrowhub.io:2222/report/159

HTH

Alexey

**Comment by dwarring** [comment]
Thanks, it looks like the failing test is system-dependent, but has also uncovered some general issues when fontconfig can't find a matching font.

Will investigate.

**Comment by melezhik** [comment]
Sure. If you want to test on alpine linux (SparkyCI),  please see my PR - https://github.com/pdf-raku/FontConfig-raku/pull/2 and please setup repo on SparkyCI , thanks

**Comment by dwarring** [comment]
Latest commit handles the situation where a FontConfig pattern doesn't match any fonts, both in the library and `basic.t` test.

Also added explicit `empty-config.t` to test the case of an empty configuration file that shouldn't match any tests.

**Comment by dwarring** [comment]
@melezhik not sure if I'm in the right place or doing the right thing.

I logged into http://sparrowhub.io:2222/ and authenticated github.

Ended up here after trying to add a repo.

![image](https://user-images.githubusercontent.com/274095/164353564-9f5464fe-db3a-4d57-a7e2-5dbb9b18062b.png)

**Comment by melezhik** [comment]
Did you click "Add repo" button?

![add repo](https://raw.githubusercontent.com/melezhik/images/master/Screen%20Shot%202022-04-20%20at%208.51.29%20PM.png)

**Comment by melezhik** [comment]
oh, it's listed in the active repos under your account, so I think you did ... let me check within SparkyCI database if your repo is added ...

**Comment by dwarring** [comment]
I just got to enter a repo name, but nothing else

**Comment by melezhik** [comment]
oh, yeah, looks like the issue is that `FontConfig-raku` belongs to `pdf-raku` org not to @dwarring  user ... , SparkyCI expects that a repo belong to user, so if one just enters a repository manually ( ignoring a suggestion list from html selection input ), Sparky ends up with a wrong github repo url.

Let me adjust it for you, but I have to think how to deal with org based repositories in the future ...

**Comment by melezhik** [comment]
I changed repo name to correct one in internal SparkyCI database, you will have to see build report soon.

Please be aware that even though repo is named as  `gh-dwarring-FontConfig-raku` , the respected GH url is `https://github.com/pdf-raku/FontConfig-raku.git`

**Comment by melezhik** [comment]
here we are! build succeeded now with your latest commit - http://sparrowhub.io:2222/report/187 🍾

**Comment by dwarring** [comment]
thanks!

**Comment by dwarring** [comment]
Fixes released with FontConfig 0.0.4
